[package]
name = "compiler-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
compiler = { path = ".." }
inkwell = { version = "0.10.0", default-features = false, features = ["llvm22-1-prefer-dynamic", "no-libffi-linking"] }

[[bin]]
name = "lexer"
path = "fuzz_targets/lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "typed"
path = "fuzz_targets/typed.rs"
test = false
doc = false
bench = false

[[bin]]
name = "interpreter"
path = "fuzz_targets/interpreter.rs"
test = false
doc = false
bench = false

[[bin]]
name = "formatter"
path = "fuzz_targets/formatter.rs"
test = false
doc = false
bench = false
